name: Meu Primeiro Workflow de CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime mensagem de boas-vindas
        run: echo "Iniciando meu primeiro job!"

      - name: Mostra o diretório de trabalho
        run: pwd

      - name: Lista arquivos no runner
        run: ls -la
